language: python

dist: xenial
python:
  - 3.7

install:
- pip install -r requirements.txt

script:
- | # freeze subl.ee
  rm -rf .frozen && mkdir .frozen
  python sublee.py freeze .frozen

- | # prepare subl.ee gh-pages
  git clone "https://sublee:$GITHUB_TOKEN@github.com/sublee/subl.ee" .gh-pages-subl.ee
  pushd .gh-pages-subl.ee
    git checkout gh-pages
    git rm -r .
    cp -r ../.frozen/* .
    echo subl.ee > CNAME
    echo "$TRAVIS_COMMIT" > version.txt
    git add .
  popd

- | # deploy subl.ee gh-pages
  pushd .gh-pages-subl.ee
    git commit -m "Deploy subl.ee $TRAVIS_COMMIT" --allow-empty
    git push -f origin gh-pages
  popd

- | # archive at archives.subl.ee
  SHORT_COMMIT="$(git rev-parse --short "$TRAVIS_COMMIT")"
  git clone "https://sublee:$GITHUB_TOKEN@github.com/sublee/subl.ee-archives"
  pushd subl.ee-archives
    cp -r ../.frozen "$SHORT_COMMIT"

    python archives.py preserve "$SHORT_COMMIT"
    python archives.py index > index.html

    git add "$SHORT_COMMIT"
    git add index.html

    git commit -m "Archive at https://archives.subl.ee/$SHORT_COMMIT"
    git push origin master > /dev/null 2>&1
  popd

branches:
  only:
  - master
