language: python
python:
- 2.7
env:
- secure: "QGo/0YV+WvtJ4Xm5guOc08pMcI1SwsBlASi9rK+MLfSnC6cLS+Mp9zyAC0SAKD4jBQFLRzVhwtGwkUnD7kP/+KGptcc3fap/w1O+w9GZt9Pa9v36CNG7a3m2+47dgJpbLoUF8rh9tt5xuf34GGECjKXxf6BDKt6KB5xtuOgh+Es="
install:
- pip install flask frozen-flask lxml markdown pyyaml
script:
- rm -rf .frozen && mkdir .frozen
- python freeze.py .frozen
after_success:
- |
  export REPO="https://$GITHUB_TOKEN@github.com/sublee/subl.ee"
  rm -rf .gh-pages && git clone -b gh-pages $REPO .gh-pages && cd .gh-pages
  git rm -r --ignore-unmatch *
  mv ../.frozen/* .
  echo subl.ee > CNAME
  git add --all
  git config user.name "Heungsub Lee" && git config user.email "sub@subl.ee"
  git commit -m "deploy subl.ee ($TRAVIS_COMMIT)"
  git push origin gh-pages > /dev/null 2>&1
