language: python
sudo: false
python:
- 2.7

install:
- pip install -r requirements.txt

script:
- | # freeze subl.ee
  rm -rf .frozen && mkdir .frozen
  python sublee.py freeze .frozen

- | # prepare subl.ee gh-pages
  mkdir .gh-pages-subl.ee
  pushd .gh-pages-subl.ee
    cp -r ../.frozen/* .
    echo subl.ee > CNAME
  popd

- | # prepare eelb.us gh-pages
  mkdir .gh-pages-eelb.us
  pushd .gh-pages-eelb.us
    cp -r ../.frozen/* .
    echo eelb.us > CNAME
    # reverse the pages
    REVERSED=$(echo '
    transform: scaleX(-1);
    -webkit-transform: scaleX(-1);
    -moz-transform: scaleX(-1);
    -o-transform: scaleX(-1);
    filter: FlipH;
    -ms-filter: FlipH;
    ' | xargs echo)
    for html in $(find . -name '*.html')
    do
      sed -i '0,/<html/s/<html/\0 style="'"$REVERSED"'"/' "$html"
    done
  popd

- | # archive at archives.subl.ee
  SHORT_COMMIT="$(git rev-parse --short "$TRAVIS_COMMIT")"
  git clone "https://sublee:$GITHUB_TOKEN@github.com/sublee/subl.ee-archives"
  pushd subl.ee-archives
    cp -r ../.frozen "$SHORT_COMMIT"

    python archives.py preserve "$SHORT_COMMIT"
    python archives.py index > index.html

    git add "$SHORT_COMMIT"
    git add index.html

    git commit -m "Archive at https://archives.subl.ee/$SHORT_COMMIT"
    git push origin master > /dev/null 2>&1
  popd

deploy:
  # subl.ee
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: .gh-pages-subl.ee
    on:
      branch: master
  # eelb.us
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: .gh-pages-eelb.us
    repo: sublee/eelb.us
    on:
      branch: master
