language: python
sudo: false
python:
- 2.7
env:
- secure: "QGo/0YV+WvtJ4Xm5guOc08pMcI1SwsBlASi9rK+MLfSnC6cLS+Mp9zyAC0SAKD4jBQFLRzVhwtGwkUnD7kP/+KGptcc3fap/w1O+w9GZt9Pa9v36CNG7a3m2+47dgJpbLoUF8rh9tt5xuf34GGECjKXxf6BDKt6KB5xtuOgh+Es="
install:
- pip install -r requirements.txt
script:
- python sublee.py verify-links
- rm -rf .frozen && mkdir .frozen
- python sublee.py freeze .frozen
after_success:
- | # deploy subl.ee
  export REPO="https://$GITHUB_TOKEN@github.com/sublee/subl.ee"
  rm -rf .gh-pages && git clone -b gh-pages $REPO .gh-pages && cd .gh-pages
  git rm -r --ignore-unmatch *
  mv ../.frozen/* .
  echo subl.ee > CNAME
  git add --all
  git config user.name "Heungsub Lee" && git config user.email "sub@subl.ee"
  git commit -m "deploy subl.ee ($TRAVIS_COMMIT)"
  git push origin gh-pages > /dev/null 2>&1
- | # deploy eelb.us
  for css in *.css
  do
    echo 'html {
      transform: scaleX(-1);
      -webkit-transform: scaleX(-1);
      -moz-transform: scaleX(-1);
      -o-transform: scaleX(-1);
      filter: FlipH;
      -ms-filter: "FlipH";
    }' >> $css
  done
  for html in $(find . -name '*.html')
  do
    echo '<script>
      var _tmp = faviconRects.l;
      faviconRects.l = faviconRects.r;
      faviconRects.r = _tmp;
      delete _tmp;
    </script>' >> $html
  done
  echo eelb.us > CNAME
  git rm -r runker
  git remote add eelbus "https://$GITHUB_TOKEN@github.com/sublee/eelb.us"
  git commit -am "reverse for eelb.us ($TRAVIS_COMMIT)"
  git push -f eelbus gh-pages > /dev/null 2>&1
