language: python
sudo: false
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- rm -rf .frozen && mkdir .frozen
- python sublee.py freeze .frozen
after_success:
- | # setup git
  git config --global user.name "Heungsub Lee"
  git config --global user.email "sub@subl.ee"
  git fetch --unshallow
- | # archive at archives.subl.ee
  SHORT_COMMIT="$(git rev-parse --short "$TRAVIS_COMMIT")"
  git clone "https://$GITHUB_TOKEN@github.com/sublee/subl.ee-archives"
  git -C subl.ee-archives checkout master
  cp -r .frozen subl.ee-archives/"$SHORT_COMMIT"
  pushd subl.ee-archives
  python archives.py preserve "$SHORT_COMMIT"
  git add "$SHORT_COMMIT"
  git commit -m "Archive to deploy at https://archives.subl.ee/$SHORT_COMMIT"
  git push origin master > /dev/null 2>&1
  popd
  rm -rf subl.ee-archives
- | # config ssh key
  openssl aes-256-cbc \
    -K $encrypted_5be8b973960e_key -iv $encrypted_5be8b973960e_iv \
    -in ../key.enc -out key -d
  chmod 600 key
  eval "$(ssh-agent -s)"
  ssh-add key
- | # deploy subl.ee
  rm -rf .gh-pages && git clone -b gh-pages "$REPO" .gh-pages && cd .gh-pages
  git rm -r --ignore-unmatch *
  mv ../.frozen/* .
  echo subl.ee > CNAME
  git add --all
  git commit -m "Deploy subl.ee ($TRAVIS_COMMIT)"
  git push origin gh-pages > /dev/null 2>&1
- | # deploy eelb.us
  REVERSED=$(echo '
  transform: scaleX(-1);
  -webkit-transform: scaleX(-1);
  -moz-transform: scaleX(-1);
  -o-transform: scaleX(-1);
  filter: FlipH;
  -ms-filter: FlipH;
  ' | xargs echo)
  for html in $(find . -name '*.html')
  do
    sed -i '0,/<html/s/<html/\0 style="'"$REVERSED"'"/' "$html"
  done
  echo eelb.us > CNAME
  git remote add eelbus "https://$GITHUB_TOKEN@github.com/sublee/eelb.us"
  git commit -am "Reverse for eelb.us ($TRAVIS_COMMIT)"
  git push -f eelbus gh-pages > /dev/null 2>&1
