language: python

dist: xenial
python:
  - 3.7

install:
- sudo apt-get install -y libcairo2-dev libpango1.0-dev
- pip install -r requirements.txt
- pip install flake8 mypy

script:
- | # lint
  flake8 sublee.py
  mypy sublee.py

- | # freeze subl.ee
  rm -rf .frozen && mkdir .frozen
  python sublee.py freeze .frozen

after_success:
- | # prepare subl.ee gh-pages
  git clone "https://sublee:$GITHUB_TOKEN@github.com/sublee/subl.ee" .gh-pages-subl.ee
  pushd .gh-pages-subl.ee
    git checkout gh-pages
    git rm -r .
    cp -r ../.frozen/* .
    echo subl.ee > CNAME
    echo "$TRAVIS_COMMIT" > version.txt
    git add .
  popd

- | # deploy subl.ee gh-pages
  pushd .gh-pages-subl.ee
    git commit -m "Deploy subl.ee $TRAVIS_COMMIT" --allow-empty
    git push -f origin gh-pages
  popd

branches:
  only:
  - master
