language: python
sudo: false
python:
- 2.7
env:
- secure: "QGo/0YV+WvtJ4Xm5guOc08pMcI1SwsBlASi9rK+MLfSnC6cLS+Mp9zyAC0SAKD4jBQFLRzVhwtGwkUnD7kP/+KGptcc3fap/w1O+w9GZt9Pa9v36CNG7a3m2+47dgJpbLoUF8rh9tt5xuf34GGECjKXxf6BDKt6KB5xtuOgh+Es="
install:
- pip install -r requirements.txt
script:
- rm -rf .frozen && mkdir .frozen
- python sublee.py freeze .frozen
after_success:
- | # identify for git
  git config --global user.name "Heungsub Lee"
  git config --global user.email "sub@subl.ee"
- | # archive at archives.subl.ee
  SHORT_COMMIT="$(git rev-parse --short "$TRAVIS_COMMIT")"
  git clone "https://$GITHUB_TOKEN@github.com/sublee/subl.ee-archives"
  cp -r .frozen subl.ee-archives/"$SHORT_COMMIT"
  pushd subl.ee-archives
  python preserve.py "$SHORT_COMMIT"
  echo '<ul>' > index.html
  git -C .. log --date=short \
    --pretty=format:'<li><a href="%h">%h</a> (%ad)</li>' >> index.html
  echo '</ul>' >> index.html
  git commit -am "Archive for archives.subl.ee ($TRAVIS_COMMIT)"
  git push origin gh-pages > /dev/null 2>&1
  popd
  rm -rf subl.ee-archives
- | # deploy subl.ee
  export REPO="https://$GITHUB_TOKEN@github.com/sublee/subl.ee"
  rm -rf .gh-pages && git clone -b gh-pages "$REPO" .gh-pages && cd .gh-pages
  git rm -r --ignore-unmatch *
  mv ../.frozen/* .
  echo subl.ee > CNAME
  git add --all
  git commit -m "Deploy subl.ee ($TRAVIS_COMMIT)"
  git push origin gh-pages > /dev/null 2>&1
- | # deploy eelb.us
  for html in $(find . -name '*.html')
  do
    sed -i '0,/<html/s/<html/\0 class="reversed"/' "$html"
  done
  echo eelb.us > CNAME
  git remote add eelbus "https://$GITHUB_TOKEN@github.com/sublee/eelb.us"
  git commit -am "Reverse for eelb.us ($TRAVIS_COMMIT)"
  git push -f eelbus gh-pages > /dev/null 2>&1
