url_root: https://subl.ee
author: Heungsub Lee
email: sub@subl.ee
copyright_year_since: 2012
google_analytics: UA-1078484-1
naver_analytics: 1275da0d21793e8
events:
  3/8: mogef       # International Women's Day
  4/16: ribbon     # Sinking of MV Sewol
